version: 2

registries:
  github-reg:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_ACCESS_TOKEN }}

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule: 
      interval: daily
    registries:
      - github-reg
